### ISSUE TITLE
Not able to configure anchor positions

### ISSUE THREAD

**Issue by easy98** [bitcraze/lps-node-firmware#54]
Hello,

I am not able to configure the anchor positions since when I click the button "get from anchors", no response. I think the connection between the cfclient and crazyflie should be fine. I am so confused about this problem. 

Thanks in advance.
![lps_configure](https://user-images.githubusercontent.com/71677216/100166710-337e5980-2e72-11eb-9c79-07cd43a82010.png)

**Comment by krichardsson** [comment]
Hi!

This happens if the anchors do not yet have a position stored in them. If this is the case you have to add the anchors manually using the "Add anchor" button in the "Anchor position configuration" dialog box. 
When you have written positions to the anchor the "get from anchors" function should work.

**Comment by krichardsson** [comment]
Related to bitcraze/crazyflie-clients-python#457

**Comment by easy98** [comment]
Thanks for quick reply,

So it seems I need to measure the anchor positions manually?

**Comment by krichardsson** [comment]
Yes, that is correct. Anchor positions must be measured manually.
We have done some experiments with automated position estimation of anchors but have not finalized it in the system.

**Comment by easy98** [comment]
OK, thanks very much!
